### ISSUE TITLE
Can you send pull request to original repository?

### ISSUE THREAD

**Issue by konifar** [a1018875550/PermissionDispatcher#2]
I don't know why you created this as other library.
I guess it's better to send pull request to original PermissionDispatchers for many users.

Can you send pull request that fix for Xiaomi phone?
Of course if you can. Because I don't know how you fix this.

**Comment by MichaelJokAr** [comment]
It's a good question;In the beginning I think this judgment for "Xiaomi" phone will change the generate java code,and those code for generate javaFile is use kotlin; I don't know the kotlin, so I request @hotchemi can add this judgment; But he refuse me, because he dosen't have "Xiaomi" phone; So I rewrite it; When I rewrite it complete, I found this judgment it does not matter for generate javaFile code; I think you are right, I will request again @hotchemi  to add this judgment; Thanks for your suggest;

**Comment by hotchemi** [comment]
@a1018875550 We don't have any plan to rewrite it to Java(Who does like it?)
But you can send a PR unless its diff does break our api interface.

And what I wanna argue is that you almost copy original readme...I do hate that idea.
In that case you should only write down about what the difference from original and which case user choose your library...

**Comment by MichaelJokAr** [comment]
@hotchemi I'm very sorry to copy your original readme,because I'm very lazy and my English is very poor; 
The diff  is <a href="https://github.com/a1018875550/PermissionDispatcher/blob/master/library/src/main/android/org.jokar.permissiondispatcher.library/PermissionUtils.java">`PermissionUtils.hasSelfPermission()` method   </a>,others is same don't need to change;
And I will add the different between the two library;

**Comment by hotchemi** [comment]
@a1018875550 Thx, understood.
Okay, I'm thinking to changing api interface without breaking anything. It would be better for both of us since I'm eager to enhance PermissionsDispatcher and plan to add some new features.

**Comment by hotchemi** [comment]
@a1018875550 As you know we original maintainer team already published addressed version so I think this repo is supposed to become deprecated or obsolete?

**Comment by MichaelJokAr** [comment]
thanks,Sorry I forget this
